GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('ascendant_engraving_matrix', 'multiblock')
        .machine((holder) => new $StarTThreadingCapableMachine(holder))
        .rotationState(RotationState.NON_Y_AXIS)
        .tooltips([ 
            Text.translate("block.start_core.gap"),
            Text.translate("block.kubejs.threading.tooltip")
        ])
        .recipeTypes(['laser_engraver', 'runic_circuitry_assembling_station', 'runic_inscribe_manipulate'])
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT_SUBTICK, $StarTRecipeModifiers.THREADING_MACHINE, $StarTRecipeModifiers.BULK_PROCESSING, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock('kubejs:ionic_engraving_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('      BCCCB      ', '     DBCCCBD     ', '    DDBCCCBDD    ', '   DDBBCCCBBDD   ', '  DDBBBCCCBBBDD  ', ' DDBBEBBBBBEBBDD ', 'BBBBBBBDDDBBBBBBB', 'CCCCCBDD DDBCCCCC', 'CCCCCBDA ADBCCCCC', 'CCCCCBDD DDBCCCCC', 'BBBBBBBDDDBBBBBBB', ' DDBBEBBBBBEBBDD ', '  DDBBBCCCBBBDD  ', '   DDBBCCCBBDD   ', '    DDBCCCBDD    ', '     DBCCCBD     ', '      BCCCB      ') 
            .aisle('     DBCCCBD     ', '   BB   F   BB   ', '  BB    F    BB  ', ' BB     F     BB ', ' B             B ', 'D      GGG      D', 'B     GDDDG     B', 'C    GDDNDDG    C', 'CFFF GDDNDDG FFFC', 'C    GDDNDDG    C', 'B     GDDDG     B', 'D      GGG      D', ' B             B ', ' BB     F     BB ', '  BB    F    BB  ', '   BB   F   BB   ', '     DBCCCBD     ') 
            .aisle('    DDBCCCBDD    ', '  BB    F    BB  ', ' B             B ', ' B             B ', 'D               D', 'D               D', 'B      CCC      B', 'C     C H C     C', 'CF    CHIHC    FC', 'C     C H C     C', 'B      CCC      B', 'D               D', 'D               D', ' B             B ', ' B             B ', '  BB    F    BB  ', '    DDBCCCBDD    ') 
            .aisle('   DDBBCCCBBDD   ', ' BB     F     BB ', ' B             B ', 'D               D', 'D               D', 'B               B', 'B      CCC      B', 'C     C H C     C', 'CF    CHIHC    FC', 'C     C H C     C', 'B      CCC      B', 'B               B', 'D               D', 'D               D', ' B             B ', ' BB     F     BB ', '   DDBBCCCBBDD   ') 
            .aisle('  DDBBBCCCBBBDD  ', ' B             B ', 'D               D', 'D               D', 'B               B', 'B               B', 'B      CCC      B', 'C     C H C     C', 'C     CHIHC     C', 'C     C H C     C', 'B      CCC      B', 'B               B', 'B               B', 'D               D', 'D               D', ' B             B ', '  DDBBBCCCBBBDD  ') 
            .aisle(' DDBBEBBBBBEBBDD ', 'D      GGG      D', 'D               D', 'B               B', 'B               B', 'E               E', 'B      CCC      B', 'BG    C   C    GB', 'BG    C I C    GB', 'BG    C   C    GB', 'B      CCC      B', 'E               E', 'B               B', 'B               B', 'D               D', 'D      GGG      D', ' DDBBBBBBBBBBBDD ') 
            .aisle('BBBBBBBDDDBBBBBBB', 'B     GDDDG     B', 'B      CCC      B', 'B      CCC      B', 'B      CCC      B', 'B      CCC      B', 'BG     JJJ     GB', 'DDCCCCJ   JCCCCDD', 'DDCCCCJ L JCCCCDD', 'DDCCCCJ   JCCCCDD', 'BG     JJJ     GB', 'B      CCC      B', 'B      CCC      B', 'B      CCC      B', 'B      CCC      B', 'B     GDDDG     B', 'BBBBBBBDDDBBBBBBB') 
            .aisle('CCCCCBDDADDBCCCCC', 'C    GDDDDDG    C', 'C     C H C     C', 'C     C H C     C', 'C     C H C     C', 'BG    C   C    GB', 'DDCCCCJ   JCCCCDD', 'DD             DD', 'ADHHH       HHHDA', 'DD             DD', 'DDCCCCJ   JCCCCDD', 'BG    C   C    GB', 'C     C H C     C', 'C     C H C     C', 'C     C H C     C', 'C    GDDDDDG    C', 'CCCCCBDDADDBCCCCC') 
            .aisle('CCCCCBDAAADBCCCCC', 'CFFF GDDDDDG FFFC', 'CF    CHIHC    FC', 'CF    CHIHC    FC', 'C     CHIHC     C', 'BG    C I C    GB', 'DDCCCCJ L JCCCCDD', ' NHHH       HHHN ', ' NIIIIL K LIIIIN ', ' NHHH       HHHN ', 'DDCCCCJ L JCCCCDD', 'BG    C I C    GB', 'C     CHIHC     C', 'CF    CHIHC    FC', 'CF    CHIHC    FC', 'CFFF GDDDDDG FFFC', 'CCCCCBDAAADBCCCCC') 
            .aisle('CCCCCBDDADDBCCCCC', 'C    GDDDDDG    C', 'C     C H C     C', 'C     C H C     C', 'C     C H C     C', 'BG    C   C    GB', 'DDCCCCJ   JCCCCDD', 'DD             DD', 'ADHHH       HHHDA', 'DD             DD', 'DDCCCCJ   JCCCCDD', 'BG    C   C    GB', 'C     C H C     C', 'C     C H C     C', 'C     C H C     C', 'C    GDDDDDG    C', 'CCCCCBDDADDBCCCCC') 
            .aisle('BBBBBBBDDDBBBBBBB', 'B     GDDDG     B', 'B      CCC      B', 'B      CCC      B', 'B      CCC      B', 'B      CCC      B', 'BG     JJJ     GB', 'DDCCCCJ   JCCCCDD', 'DDCCCCJ L JCCCCDD', 'DDCCCCJ   JCCCCDD', 'BG     JJJ     GB', 'B      CCC      B', 'B      CCC      B', 'B      CCC      B', 'B      CCC      B', 'B     GDDDG     B', 'BBBBBBBDDDBBBBBBB') 
            .aisle(' DDBBEBBBBBEBBDD ', 'D      GGG      D', 'D               D', 'B               B', 'B               B', 'E               E', 'B      CCC      B', 'BG    C   C    GB', 'BG    C I C    GB', 'BG    C   C    GB', 'B      CCC      B', 'E               E', 'B               B', 'B               B', 'D               D', 'D      GGG      D', ' DDBBBBBBBBBBBDD ') 
            .aisle('  DDBBBCCCBBBDD  ', ' B             B ', 'D               D', 'D               D', 'B               B', 'B               B', 'B      CCC      B', 'C     C H C     C', 'C     CHIHC     C', 'C     C H C     C', 'B      CCC      B', 'B               B', 'B               B', 'D               D', 'D               D', ' B             B ', '  DDBBBCCCBBBDD  ') 
            .aisle('   DDBBCCCBBDD   ', ' BB     F     BB ', ' B             B ', 'D               D', 'D               D', 'B               B', 'B      CCC      B', 'C     C H C     C', 'CF    CHIHC    FC', 'C     C H C     C', 'B      CCC      B', 'B               B', 'D               D', 'D               D', ' B             B ', ' BB     F     BB ', '   DDBBCCCBBDD   ') 
            .aisle('    DDBCCCBDD    ', '  BB    F    BB  ', ' B             B ', ' B             B ', 'D               D', 'D               D', 'B      CCC      B', 'C     C H C     C', 'CF    CHIHC    FC', 'C     C H C     C', 'B      CCC      B', 'D               D', 'D               D', ' B             B ', ' B             B ', '  BB    F    BB  ', '    DDBCCCBDD    ') 
            .aisle('     DBCCCBD     ', '   BB   F   BB   ', '  BB    F    BB  ', ' BB     F     BB ', ' B             B ', 'D      GGG      D', 'B     GDDDG     B', 'C    GDDDDDG    C', 'CFFF GDDDDDG FFFC', 'C    GDDDDDG    C', 'B     GDDDG     B', 'D      GGG      D', ' B             B ', ' BB     F     BB ', '  BB    F    BB  ', '   BB   F   BB   ', '     DBCCCBD     ') 
            .aisle('      BCCCB      ', '     DBCCCBD     ', '    DDBCCCBDD    ', '   DDBBCCCBBDD   ', '  DDBBBCCCBBBDD  ', ' DDBBEBB@BBEBBDD ', 'BBBBBBBDDDBBBBBBB', 'CCCCCBDDADDBCCCCC', 'CCCCCBDAAADBCCCCC', 'CCCCCBDDADDBCCCCC', 'BBBBBBBDDDBBBBBBB', ' DDBBEBBMBBEBBDD ', '  DDBBBCCCBBBDD  ', '   DDBBCCCBBDD   ', '    DDBCCCBDD    ', '     DBCCCBD     ', '      BCCCB      ') 
            .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            .where('A', Predicates.blocks('kubejs:nyanium_heat_escape_casing'))
            .where('B', Predicates.blocks('kubejs:ionic_engraving_casing')
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(0).setMaxGlobalLimited(20))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(0).setMaxGlobalLimited(20))
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(0).setMaxGlobalLimited(20))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
            .where('C', Predicates.blocks('kubejs:draco_resilient_fusion_glass'))
            .where('D', Predicates.blocks('kubejs:draco_assembly_grating'))
            .where('E', Predicates.blocks('kubejs:nyanium_engine_intake_casing'))
            .where('F', Predicates.blocks('gtceu:superconducting_coil'))
            .where('G', Predicates.blocks('gtceu:palladium_substation'))
            .where('H', Predicates.blocks('gtceu:expetidalloy_d_17_frame'))
            .where('I', Predicates.blocks('kubejs:melodium_casing'))
            .where('J', Predicates.blocks('start_core:advanced_fusion_coil'))
            .where('K', Predicates.blocks('kubejs:inscribe_casing'))
            .where('L', Predicates.blocks('kubejs:laser_casing'))
            .where('M', Predicates.blocks('start_core:threading_controller'))
            .where('N', $StarTThreadingStatBlocks.threadingStatBlocks())
            .where(' ', Predicates.any())
            .build())
        
        // .pattern(definition => FactoryBlockPattern.start()
        //     .aisle('   BCCCB   ', '   BC CB   ', '   BCDCB   ', '   BCDCB   ', '   BC CB   ', '   BCCCB   ', '   BBBBB   ', '   B   B   ', '   B   B   ', '   B   B   ', '   BBBBB   ', '    CCC    ', '    C C    ', '    CCC    ', '   BBBBB   ', '     B     ', '     B     ', '           ', '           ') 
        //     .aisle('  CCCCCCC  ', '  CCCECCC  ', '  CCCFCCC  ', '  CCCFCCC  ', '    CECG   ', '    CFCG   ', '  BBCCCBB  ', '    CCC    ', '           ', '    CCC    ', '  BBCCCBB  ', '   BCCCB   ', '   BCECB   ', '   BCCCB   ', '  BBGGGBB  ', '    GGG    ', '     B     ', '     B     ', '           ') 
        //     .aisle(' CCDDDDDCC ', ' CC  F  CC ', ' CCFFFFFCC ', ' CC  F  CC ', '  GG F  G  ', '  GG F  G  ', ' BBG D GBB ', '   G D G   ', '    DDD    ', '   G   G   ', ' BBG   GBB ', '  GG   GG  ', '  GG H GG  ', '  GG   GG  ', ' BBG   GBB ', '   G   G   ', '    GGG    ', '     B     ', '     B     ') 
        //     .aisle('BCDDDDDDDCB', 'BC       CB', 'BCF     FCB', 'BC       CB', 'B G      GB', 'B G      GB', 'BBG     GBB', 'B G     G B', 'B  D   D  B', 'B G     G B', 'BBG     GBB', ' BG     GB ', ' BG  H  GB ', ' BG     GB ', 'BBG     GBB', '  G     G  ', '   G   G   ', '    GGG    ', '     B     ') 
        //     .aisle('CCDDDDDDDCC', 'CC       CC', 'CCF     FCC', 'CC       CC', 'CC       CC', 'CC       CC', 'BC       CB', ' C       C ', '  D     D  ', ' C       C ', 'BC       CB', 'CC       CC', 'CC       CC', 'CC       CC', 'BG       GB', ' G       G ', '  G     G  ', '   GGGGG   ', '     B     ') 
        //     .aisle('CCDDDDDDDCC', ' EF     FE ', 'DFF     FFD', 'DFF     FFD', ' EF     FE ', 'CFF  I  FFC', 'BCD     DCB', ' CD     DC ', '  D  J  D  ', ' C       C ', 'BC       CB', 'CC   I   CC', ' EHH   HHE ', 'CC       CC', 'BG       GB', 'BG       GB', 'BBG     GBB', ' BBGGGGGBB ', '  BBBBBBB  ') 
        //     .aisle('CCDDDDDDDCC', 'CC       CC', 'CCF     FCC', 'CC       CC', 'CC       CC', 'CC       CC', 'BC       CB', ' C       C ', '  D     D  ', ' C       C ', 'BC       CB', 'CC       CC', 'CC       CC', 'CC       CC', 'BG       GB', ' G       G ', '  G     G  ', '   GGGGG   ', '     B     ') 
        //     .aisle('BCDDDDDDDCB', 'BC       CB', 'BCF     FCB', 'BC       CB', 'B G     G B', 'B G     G B', 'BBG     GBB', 'B G     G B', 'B  D   D  B', 'B G     G B', 'BBG     GBB', ' BG     GB ', ' BG  H  GB ', ' BG     GB ', 'BBG     GBB', '  G     G  ', '   G   G   ', '    GGG    ', '     B     ') 
        //     .aisle(' CCDDDDDCC ', ' CC  F  CC ', ' CCFFFFFCC ', ' CC  F  CC ', '  GG F GG  ', '  GG F GG  ', ' BBG D GBB ', '   G D G   ', '    DDD    ', '   G   G   ', ' BBG   GBB ', '  GG   GG  ', '  GG H GG  ', '  GG   GG  ', ' BBG   GBB ', '   G   G   ', '    GGG    ', '     B     ', '     B     ') 
        //     .aisle('  CCCCCCC  ', '  CCCFCCC  ', '  CCCFCCC  ', '  CCCFCCC  ', '    CFC    ', '    CFC    ', '  BBCCCBB  ', '    CCC    ', '           ', '    CCC    ', '  BBCCCBB  ', '   BCCCB   ', '   BCKCB   ', '   BCCCB   ', '  BBGGGBB  ', '    GGG    ', '     B     ', '     B     ', '           ') 
        //     .aisle('   BCCCB   ', '   BCCCB   ', '   BCCCB   ', '   BC@CB   ', '   BCCCB   ', '   BCCCB   ', '   BBBBB   ', '   B   B   ', '   B   B   ', '   B   B   ', '   BBBBB   ', '    CCC    ', '    C C    ', '    CCC    ', '   BBBBB   ', '     B     ', '     B     ', '           ', '           ') 
        //     .where(' ', Predicates.any())
        //     .where('B', Predicates.blocks('gtceu:expetidalloy_d_17_frame'))
        //     .where('C', Predicates.blocks('kubejs:ionic_engraving_casing')
        //         .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(0).setMaxGlobalLimited(20))
        //         .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(0).setMaxGlobalLimited(20))
        //         .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(0).setMaxGlobalLimited(20))                
        //         .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
        //         .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
        //         .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
        //     .where('D', Predicates.blocks('kubejs:draco_assembly_grating'))
        //     .where('E', $StarTThreadingStatBlocks.threadingStatBlocks())
        //     .where('F', Predicates.blocks('kubejs:superdense_assembly_control_casing'))
        //     .where('G', Predicates.blocks('kubejs:draco_resilient_fusion_glass'))
        //     .where('H', Predicates.blocks('start_core:advanced_fusion_coil'))
        //     .where('I', Predicates.blocks('kubejs:laser_casing'))
        //     .where('J', Predicates.blocks('kubejs:inscribe_casing'))
        //     .where('K', Predicates.blocks('start_core:threading_controller'))
        //     .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            // .build())
        .workableCasingModel('kubejs:block/casings/threading/ionic_engraving_casing',
            'gtceu:block/machines/laser_engraver');

});